services:
  # MkDocs主服务
  mkdocs:
    image: squidfunk/mkdocs-material:latest  # 使用官方镜像
    container_name: mkdocs
    restart: unless-stopped
    ports:
      - "2004:8000"
    volumes:
      - .:/docs
    command: serve --dev-addr=0.0.0.0:8000  # 添加启动命令
    environment:
      - TZ=Asia/Shanghai
    networks:
      - docs-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # 辅助更新服务
  docs-updater:
    build:
      context: ./docs_assistant
      dockerfile: Dockerfile
    container_name: docs-updater
    restart: unless-stopped
    volumes:
      - .:/app/docs
    environment:
      - UPDATE_INTERVAL=1800  # 30分钟更新一次
      - GITHUB_REPO=Calcium-Ion/new-api
      - DOCS_DIR=/app/docs
      - USE_PROXY=false
      - GITHUB_PROXY=https://api2.aimage.cc/proxy
      - TZ=Asia/Shanghai
    networks:
      - docs-network
    depends_on:
      mkdocs:
        condition: service_healthy

networks:
  docs-network:
    driver: bridge