site_name: New API Docs
site_url: https://docs.newapi.pro
site_author: QuantumNous
site_description: 新一代大模型网关与AI资产管理系统

# Repository
repo_name: QuantumNous/new-api
repo_url: https://github.com/QuantumNous/new-api

theme:
  name: material
  language: zh
  custom_dir: newapi/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate 
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.expand
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 切换到系统主题
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

extra:
  alternate:
    - name: 中文
      link: /
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/QuantumNous/new-api
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/calciumion/new-api
  analytics:
    provider: google
    property: G-VHJ4VGJB6N
  consent:
    title: Cookie 同意
    description: >- 
      我们使用 Cookie 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到他们要找的内容。
    cookies:
      analytics: Google Analytics
  generator: false

nav:
  - 首页: index.md
  - 开始使用: getting-started.md
  - 维基百科:
    - 📖 维基百科: wiki/index.md
    - 📚 基本概念:
      - 项目介绍: wiki/project-introduction.md
      - 特性说明: wiki/features-introduction.md
      - 技术架构: wiki/technical-architecture.md
    - 📝 项目记录:
      - 更新日志: wiki/changelog.md
      - 特别鸣谢: wiki/special-thanks.md
  - 安装指南:
    - 🏠 安装指南: installation/index.md
    - 🔧 部署方式:
      - Docker 部署: installation/docker-installation.md
      - Docker Compose 部署: installation/docker-compose-installation.md
      - 宝塔面板部署: installation/bt-docker-installation.md
      - 集群部署: installation/cluster-deployment.md
      - 本地开发部署: installation/local-development.md
    - ⚙️ 配置与维护:
      - 系统更新: installation/system-update.md
      - 环境变量配置: installation/environment-variables.md
      - Docker Compose 配置文件: installation/docker-compose-yml.md
  - 接口文档:
    - 🏠 接口文档: api/index.md
    - 中继接口:
      - 💬 聊天（Chat）:
        - OpenAI 格式（Chat Completions）: api/openai-chat.md
        - OpenAI 格式（Responses）: api/openai-responses.md
        - Anthropic 格式（Messages）: api/anthropic-chat.md
        - Deepseek reasoning 格式（Reasoning Content）: api/deepseek-reasoning-chat.md
        - 🆕 Google Gemini 格式（Generate Content）: api/google-gemini-chat.md
      - 🔤 嵌入（Embeddings）:
        - OpenAI 格式: api/openai-embedding.md
      - 🔄 重排序（Rerank）:
        - Jina AI 格式: api/jinaai-rerank.md
        - Cohere 格式: api/cohere-rerank.md
        - Xinference 格式: api/xinference-rerank.md
      - ⚡ 实时对话（Realtime）:
        - OpenAI 格式: api/openai-realtime.md
      - 🖼️ 图像（Image）:
        - OpenAI 格式（Image）: api/openai-image.md
        - Midjourney 格式（Midjourney Proxy/Midjourney Proxy Plus）: api/midjourney-proxy-image.md
      - 🔊 音频（Audio）:
        - OpenAI 格式: api/openai-audio.md
      - 🎵 音乐（Music）:
        - Suno API 格式: api/suno-music.md
    - 前端接口:
      - 敬请期待: coming-soon.md
  - 帮助支持:
    - 🏠 帮助支持: support/index.md
    - 🌐 社区交流: support/community-interaction.md
    - 🐛 反馈问题: support/feedback-issues.md
    - ❓ 常见问题: support/faq.md
    - ☕ 请我们喝咖啡: support/buy-us-a-coffee.md

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags
  - i18n:
      default_language: zh
      languages:
        - locale: zh
          name: 中文
        - locale: en
          name: English
      reconfigure_material: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2025 Quantum Nous. All Rights Reserved.