site_name: New API
site_description: 新一代大模型网关与AI资产管理系统
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  logo: assets/logo.png

nav:
  - 首页: index.md
  - 快速开始:
    - 部署指南: deployment.md
    - 宝塔面板部署: bt-deployment.md
  - 功能特性:
    - 模型支持: models.md
    - 配置说明: configuration.md
    - 渠道重试: retry.md
  - API集成:
    - Midjourney接入: midjourney.md
    - Suno接入: suno.md
    - Rerank接入: rerank.md
  - 其他:
    - 相关项目: related-projects.md
    - 交流社区: community.md

plugins:
  - search
  - social
  - tags
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: datetime

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - footnotes

copyright: Copyright &copy; 2024 New API Team

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Calcium-Ion/new-api
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/calciumion/new-api
