site_name: New API
site_url: https://github.com/Calcium-Ion/new-api
site_author: New API Team
site_description: 新一代大模型网关与AI资产管理系统

# Repository
repo_name: Calcium-Ion/new-api
repo_url: https://github.com/Calcium-Ion/new-api

theme:
  name: material
  language: zh
  custom_dir: newapi/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate 
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.expand
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 切换到系统主题
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

nav:
  - 首页: index.md
  # 负责系统部署和配置说明
  - 部署与配置: 
    - 项目介绍: introduction.md
  # 负责用户系统使用说明
  - 用户指南:
    - 敬请期待: coming-soon.md
  # 负责接口文档说明
  - 接口文档:
    - 中继接口:
      - 💬 聊天（Chat）:
        - OpenAI 格式（Chat Completions）: openai-chat.md
        - Anthropic 格式（Messages）: anthropic-chat.md
        - Deepseek reasoning 格式（类Chat Completions）: deepseek-reasoning-chat.md
      - 🔤 嵌入（Embeddings）:
        - OpenAI 格式: openai-embedding.md
      - 🔄 重排序（Rerank）:
        - Jina AI 格式: jinaai-rerank.md
      - ⚡ 实时对话（Realtime）:
        - OpenAI 格式: openai-realtime.md
      - 🖼️ 图像（Image）:
        - OpenAI 格式（Dall·E）: openai-image.md
        - Midjourney 格式（Midjourney Proxy/Midjourney Proxy Plus）: midjourney-proxy-image.md
      - 🔊 音频（Audio）:
        - OpenAI 格式: openai-audio.md
      - 🎵 音乐（Music）:
        - Suno API 格式: suno-music.md
    - 前端接口:
      - 敬请期待: coming-soon.md
  # 负责其他说明
  - 帮助支持:
    - 敬请期待: coming-soon.md

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - social
  - tags
  # - minify:
  #     minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2025 Quantum Nous. All Rights Reserved. 量子智元公司 版权所有

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Calcium-Ion/new-api
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/calciumion/new-api
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie 同意
    description: >- 
      我们使用 Cookie 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到他们要找的内容。
    cookies:
      analytics: Google Analytics
  generator: false