site_name: New API Docs
site_url: https://nd.aiis.cc
site_author: 量子智元
site_description: 新一代大模型网关与AI资产管理系统

# Repository
repo_name: Calcium-Ion/new-api
repo_url: https://github.com/Calcium-Ion/new-api

theme:
  name: material
  language: zh
  custom_dir: newapi/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate 
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.expand
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 切换到系统主题
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

nav:
  - 首页: index.md
  - 开始使用: getting-started.md
  - 维基百科:
    - 📖 项目介绍: wiki/project-introduction.md
    - ✨ 特性说明: wiki/features-introduction.md
    - 🏗️ 技术架构: wiki/technical-architecture.md
    - 📝 更新日志: wiki/changelog.md
    - 🤖 模型支持: wiki/supported-models.md
    - 🗺️ 路线图:
      - 2025年: wiki/2025-roadmap.md
    - 🙏 特别鸣谢: wiki/special-thanks.md
  - 安装指南:
    - 🔧 部署方式:
      - Docker 部署: installation/docker-installation.md
      - Docker Compose 部署: installation/docker-compose-installation.md
      - 宝塔面板部署: installation/bt-docker-installation.md
      - 集群部署: installation/cluster-deployment.md
    - ⚙️ 配置与维护:
      - 系统更新: installation/system-update.md
      - 环境变量配置: installation/environment-variables.md
      - Docker Compose 配置文件: installation/docker-compose-yml.md
  - 用户指南:
    - 应用接入:
      - 1️⃣ NextChat: user-guide/nextchat-integration.md
      - 2️⃣ Cursor: user-guide/cursor-integration.md
    - 系统操作:
      - 全局:
        - 🌐 多语言（i18n）: user-guide/i18n.md
        - 🎨 主题切换: user-guide/theme-switch.md
      - 普通用户:
        - 👤 注册与登录: user-guide/user-registration-and-login.md
        - 💰 模型定价: user-guide/model-pricing.md
        - ℹ️ 关于: user-guide/about.md
        - 控制台:
          - 🎮 Playground: user-guide/playground.md
          - 💬 聊天: user-guide/chat.md
          - 🔑 令牌管理: user-guide/token-management.md
          - 📊 数据看板: user-guide/dashboard.md
          - 💳 钱包: user-guide/wallet.md
          - 📝 日志: user-guide/logs.md
          - 🎨 绘画: user-guide/painting.md
          - ⏱️ 异步任务: user-guide/async-tasks.md
          - 设置:
            - ⚙️ 个人设置: user-guide/personal-settings.md
      - 管理员:
        - 控制台:
          - 🔌 渠道管理: user-guide/channel-management.md
          - 🎟️ 兑换码管理: user-guide/redeem-code-management.md
          - 👥 用户管理: user-guide/user-management.md
          - 设置:
            - 📈 运营设置: user-guide/operation-settings.md
            - 🚦 速率限制设置: user-guide/rate-limit-settings.md
            - 🖥️ 系统设置: user-guide/system-settings.md
            - 🔧 其他设置: user-guide/other-settings.md
  - 接口文档:
    - 接口介绍: api-docs/interface-introduction.md
    - 中继接口:
      - 💬 聊天（Chat）:
        - OpenAI 格式（Chat Completions）: api-docs/openai-chat.md
        - Anthropic 格式（Messages）: api-docs/anthropic-chat.md
        - Deepseek reasoning 格式（类Chat Completions）: api-docs/deepseek-reasoning-chat.md
      - 🔤 嵌入（Embeddings）:
        - OpenAI 格式: api-docs/openai-embedding.md
      - 🔄 重排序（Rerank）:
        - Jina AI 格式: api-docs/jinaai-rerank.md
        - Cohere 格式: api-docs/cohere-rerank.md
      - ⚡ 实时对话（Realtime）:
        - OpenAI 格式: api-docs/openai-realtime.md
      - 🖼️ 图像（Image）:
        - OpenAI 格式（Dall·E）: api-docs/openai-image.md
        - Midjourney 格式（Midjourney Proxy/Midjourney Proxy Plus）: api-docs/midjourney-proxy-image.md
      - 🔊 音频（Audio）:
        - OpenAI 格式: api-docs/openai-audio.md
      - 🎵 音乐（Music）:
        - Suno API 格式: api-docs/suno-music.md
    - 前端接口:
      - 敬请期待: coming-soon.md
  - 帮助支持:
    - 🌐 社区交流: support/community-interaction.md
    - 🐛 反馈问题: support/feedback-issues.md
    # - 📧 联系我们: support/contact-us.md
    - ❓ 常见问题: support/faq.md
    - ☕ 给我们买一杯咖啡: support/buy-us-a-coffee.md

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - social
  - tags
  # - minify:
  #     minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# copyright: Copyright &copy; 2025 Quantum Nous. All Rights Reserved. 量子智元公司 版权所有
copyright: Copyright &copy; 2025 New API. All Rights Reserved.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Calcium-Ion/new-api
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/calciumion/new-api
  analytics:
    provider: google
    property: G-VHJ4VGJB6N
  consent:
    title: Cookie 同意
    description: >- 
      我们使用 Cookie 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到他们要找的内容。
    cookies:
      analytics: Google Analytics
  generator: false