site_name: New API
site_url: https://github.com/Calcium-Ion/new-api
site_author: New API Team
site_description: 新一代大模型网关与AI资产管理系统

# Repository
repo_name: Calcium-Ion/new-api
repo_url: https://github.com/Calcium-Ion/new-api

theme:
  name: material
  language: zh
  # custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate 
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.expand
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 切换到系统主题
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

nav:
  - 首页: index.md
  - 快速开始:
    - 部署指南: deployment.md
    - 宝塔面板部署: bt-deployment.md
    - 基础配置: configuration.md
  - 核心功能:
    - 模型支持: models.md
    - 重试机制: retry.md
  - API集成:
    - API使用示例: api-examples.md
    - Midjourney接入: midjourney.md
    - Suno接入: suno.md
    - Rerank接入: rerank.md
  - 帮助支持:
    - 常见问题: faq.md
    - 相关项目: related-projects.md
    - 交流社区: community.md

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - social
  - tags
  # - minify:
  #     minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2024 New API Team

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Calcium-Ion/new-api
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/calciumion/new-api
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie 同意
    description: >- 
      我们使用 Cookie 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到他们要找的内容。
    cookies:
      analytics: Google Analytics
  generator: false
